### ISSUE TITLE
FMU model

### ISSUE THREAD

**Issue by sy10010** [modelica/www.modelica.org#126]
need FMU model files related to the industrial sector, preferably for aircraft, automobiles, and ships.

**Comment by chrbertsch** [comment]
This is a repository for the Website of the Modelica Association.
Please use one of the 220+ tools supporting FMI listed on https://fmi-standard.org/tools/ to create your FMUs, or use e.g. StackOvervflow tagged "FMI" (https://stackoverflow.com/questions/tagged/fmi) to get help from the community.
