### ISSUE TITLE
Why is not shown last realease of the Physiolibrary  in modelica web pages?

### ISSUE THREAD

**Issue by MarekMatejak** [modelica/www.modelica.org#37]
Hello Dietmar,
I did not see you in the conference. Hope you are well.
Please check me the version of Physiolibrary in modelica pages - it should be 3.0.0, see:
https://github.com/modelica-3rdparty/Physiolibrary/releases/tag/v3.0.0
Thank you
Marek

**Comment by dietmarw** [comment]
The generation of the listing on modelica.org/libraries is out of my hands. I don't know what script the MA now runs in order to keep it up to date with modelica-3rdparty (which I keep updated). @sjoelund might know.

**Comment by sjoelund** [comment]
The script was broken by accident when pushing the new webpage design. And the library listing was some version that was kept at the forked version of the repository or something so it was outdated as well. At least you found it fast (the webpage was updated right before the conference)

**Comment by sjoelund** [comment]
The libraries should update automatically again now (and I fixed the CSS, etc)
