### ISSUE TITLE
Add open-source library [openimdml] to the library listing

### ISSUE THREAD

**Issue by lvanfretti** [modelica/www.modelica.org#38]
Hello!
Could you add the following library to the listing: https://github.com/alsetlab/openimdml
Thank you!
Luigi

**Comment by dietmarw** [comment]
Done. Should appear within 24h on the website listing. You might want to consider creating a proper release so that is also listed as a download option.

**Comment by lvanfretti** [comment]
@dietmarw I thought we have a proper release: https://github.com/ALSETLab/OpenIMDML/releases/tag/v1.0.0
Please let us know if there is any mistake.

**Comment by dietmarw** [comment]
So everything is fine. I simply overlooked it.
@sjoelund It looks to me that the script to update the listing on modelica.org is still not getting run periodically.
