### ISSUE TITLE
Update publication list

### ISSUE THREAD

**Issue by HansOlsson** [modelica/www.modelica.org#44]
Issues:
- The newest article on https://modelica.org/publications/articles/ is from 2010
- In contrast Modelica conference articles are found in https://modelica.org/events/ and not under publications. If someone is new to Modelica they might not understand that some publications are under "events".
- The older conference pages are a mess:
  -  Weird case handling: last paper on https://modelica.org/events/conference2005/ is https://modelica.org/events/Conference2005/online_proceedings/Session7/Session7c3.pdf which links to the proceedings at https://modelica.org/events/Conference2005/ and **the latter is a dead-link**.
  -  Who cares which session a paper was presented in? (On the other hand we shouldn't spend too much time on it, modifying the links may cause problems, and searching is quick enough.)

It would be good to add newer articles, and certainly to fix the links.

For the conference series: I'm not sure exactly how to organize it, but one possibility would be:

- Move Modelica conference series to publications, "conference series" (preferably without moving the files).
- Under https://modelica.org/events/ link to it - and keep the rest of the page.

**Comment by HansOlsson** [comment]
Looking more: 
- Searching for "Modelica" articles gives about 4,490 hits; https://www.semanticscholar.org/search?q=modelica . I don't think we have the resources to update the list of articles and papers - so either delete it or add that these are only kept for historic interest, and there are too many new ones added to list all.
- https://modelica.org/publications/papers/ is also problematic 
 - It says that the Modelica conference papers aren't included, _but doesn't even give a link_! And the 14th Modelica conference and the American and Asian ones are still listed; as well as some EOOLT (but not all); as if we want to promote everything but Modelica conferences.
 - After 2007 there's a considerable drop-off; similarly as for articles.

**Comment by dzimmer** [comment]
I would simplify things and remove good chunks from the Publications web page. All what we put up, we need to maintain: I suggest to:
- Remove Articles
- Remove Theses
- Remove Papers
- Change Books to Literature (which means selected literature. Recommended books and maybe a few recommended articles)
- Move Conference Proceededings from the Event page to Proceedings under Publications
- Leave tutorials there as temporary fix. 

Once we have actually good tutorials, the will be integrated into language.
