### ISSUE TITLE
News refers to past event

### ISSUE THREAD

**Issue by beutlich** [modelica/www.modelica.org#46]
The News is outdated.

![grafik](https://github.com/modelica/www.modelica.org/assets/14896695/7e6d87ef-8762-49b0-9edf-55f5cd37e451)

By the way, there could be some link to https://newsletter.modelica.org/.

**Comment by t-sommer** [comment]
Feel free to make a PR for a news post to supersede this one.

**Comment by beutlich** [comment]
Why was this closed as wontfix?

**Comment by chrbertsch** [comment]
I agree with Torsten's understanding, that the news headline just refers to the latest new post.
Just add new news article to https://github.com/modelica/www.modelica.org/tree/master/content/news.
This could e.g. be a link to  the latest newsletter https://newsletter.modelica.org/2022-03/index.
@filip-jezek: could you perhaps take care of creating a short news article announcing each new newsletter? Thanks!
