### ISSUE TITLE
Too many link styles on modelica.org

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/www.modelica.org#50]
Overall, I really like the new modelica.org look, but one thing made me react immediately; namely the different ways of linking to Modelica language and the other Modelica related topics.

How about turning this into the same style as _Modelica Standard Library_ and friends?
https://github.com/modelica/www.modelica.org/blob/3f2aa3a2a40fc7d421d296c501a9a61ee97f285d/content/_index.html#L22

**Comment by t-sommer** [comment]
Solved with 279e67330da5318aa899a0f1c816150a662ab86b.
