### ISSUE TITLE
Add open-source library [LCC_HVDC] to the library listing

### ISSUE THREAD

**Issue by MohammadBabaeifar** [modelica/www.modelica.org#51]
A library for simulating line-commutated converter high voltage direct current (LCC HVDC) systems.
https://github.com/MohammadBabaeifar/LCC_HVDC

**Comment by MohammadBabaeifar** [comment]
[https://github.com/MohammadBabaeifar/LCC_HVDC](url)

**Comment by dietmarw** [comment]
Done. Should appear within 24 hours.

**Comment by MohammadBabaeifar** [comment]
Thank you very much Mr. Dietmar Winkler.

**Comment by casella** [comment]
For the record, which "listing" are you referring to?

**Comment by dietmarw** [comment]
https://modelica.org/libraries/ though I can currently not see the LCC_HVDC appearing. @sjoelund is the script hanging again?

**Comment by sjoelund** [comment]
The script did run, but there are no tags. https://github.com/modelica/www.modelica.org/actions/runs/6649903294/job/18069130595#step:5:115

**Comment by dietmarw** [comment]
But that should not keep the library from being listed. Just that there is no blue button for download

**Comment by sjoelund** [comment]
Yes, I have looked at the code and that's what should have happened. But it didn't :D

**Comment by sjoelund** [comment]
I feel stupid after trying to debug this now. It's the building of the web pages that is broken...

**Comment by sjoelund** [comment]
https://github.com/orgs/community/discussions/25702
