### ISSUE TITLE
Weird end for https://modelica.org/events/

### ISSUE THREAD

**Issue by HansOlsson** [modelica/www.modelica.org#54]
As noted in #44 
https://modelica.org/events/
ends with:

![image](https://github.com/modelica/www.modelica.org/assets/13217430/1d30e804-b70b-43ce-a8da-345df7041491)

I cannot see that in the markdown code so it is something else triggering it.

**Comment by t-sommer** [comment]
Fixed with 59babe1035f9d4f98f7f77cf5b64999356a53736.
