### ISSUE TITLE
Add deprecated ModelicaLicense2

### ISSUE THREAD

**Issue by GallLeo** [modelica/www.modelica.org#65]
Many people still link to 
http://www.modelica.org/licenses/ModelicaLicense2

So, I think we should re-upload the old license.
With a note, that it should not be used for new libraries.
Alternatives are BSB 3-clause (like MSL) or the extended version of BSD (like Buildings, which simplifies accepting pull requests).

**Comment by beutlich** [comment]
Is this a duplicate of #45?

**Comment by t-sommer** [comment]
Fixed with #84.
