### ISSUE TITLE
Add open-source library DLR Thermofluid Stream Library to the library listing

### ISSUE THREAD

**Issue by dzimmer** [modelica/www.modelica.org#73]
**Link:** https://github.com/DLR-SR/ThermofluidStream

**Description:** The DLR Thermofluid Stream Library is a free open-source library for the robust modeling of complex thermofluid architectures. Designed to be easy to use and easy to adapt and enriched by a number of examples, this library can be used as basis for many different applications such as thermal management of electric cars, power plants, or building physics.

**Comment by dietmarw** [comment]
The library has already been added a long time ago. See https://github.com/modelica-3rdparty/ThermofluidStream  
As for why it is not shown on modelica.org/libraries is something that the MA webmaster needs to figure out.
