### ISSUE TITLE
Add book to publications?

### ISSUE THREAD

**Issue by MABackoffice** [modelica/www.modelica.org#74]
I (Sonja) have received an email about a book:

Link to book (in German): https://link.springer.com/book/10.1007/978-3-658-25089-8
"about bond-graphs, Modelica and dynamic solvers. Chapter 6 and 7 are pretty exclusively related to Modelica. Also Chapter 8 covers solvers for dynamic simulation."

Should it be added to the publications list?

**Comment by AHaumer** [comment]
IMHO yes. I know both authors and the book.

**Comment by MartinOtter** [comment]
Yes, please add it.

**Comment by MABackoffice** [comment]
@t-sommer 
Could you please help me put the cover of the book in the code? So far it shows only the written title.

**Line 9 here:**
content/publications/books.md 

**Book cover:**
https://link.springer.com/book/10.1007/978-3-658-25089-8


Sorry, I do not know how to add it myself.

![grafik](https://github.com/modelica/www.modelica.org/assets/40261100/7a3b684d-2373-49ea-adb0-3ab77538e8ea)
Here is an example for Atiyah's book.

**Comment by t-sommer** [comment]
Fixed with 010f886b964cb864ebf415b594214f3db5564931.
