### ISSUE TITLE
Add YouTube and LinkedIn

### ISSUE THREAD

**Issue by MABackoffice** [modelica/www.modelica.org#90]
@dzimmer suggested to add:
https://www.youtube.com/@modelicaassociation

https://www.linkedin.com/company/modelica-association/posts/?feedView=all

Maybe here? At the lower banner of https://modelica.org/? 
![grafik](https://github.com/modelica/www.modelica.org/assets/40261100/c5d0c155-5cc6-4eee-8e6d-3cc786ad6594)

**Comment by dzimmer** [comment]
Could be a good place. However, I will care about this myself in the next few days and come up with concrete pull requests or the like

**Comment by beutlich** [comment]
What about X (fka Twitter)? https://x.com/modelica

**Comment by t-sommer** [comment]
Fixed with 9933357dc3738df1f66d7400c5ea1aafe6b984e5.
