### ISSUE TITLE
remove projects.

### ISSUE THREAD

**Issue by dzimmer** [modelica/www.modelica.org#96]
https://modelica.org/community/projects/

I fail to see the value of this information for the general audience. Given the lack of maintenance on important parts of the web-page, I think we shall remove it.

**Comment by MartinOtter** [comment]
Its by far the best summary of the research projects performed in the past in the area of the Modelica Association. It indicates in particular how much money was put into the development. Looks like useful information to me.
I checked and the only link that did not work is mosim.eu, which should be updated. Further, OpenSCALING should be added. Seems to be not much effort.

**Comment by casella** [comment]
> I fail to see the value of this information for the general audience. Given the lack of maintenance on important parts of the web-page, I think we shall remove it.

Respectfully disagree. These projects send a signal about the community being supported and Modelica not being on track for a dead end. Also, old projects can just stay there.

I would only suggest to
- add more recent projects
- check links
- order projects from more newest to oldest, rather than the other way round

**Comment by HansOlsson** [comment]
However, even if we keep this part after those updates, I think we should then clear out the other non-maintained parts (publications etc) both to signal a change and to make it easier to focus on the relevant things.

**Comment by dzimmer** [comment]
I can fix (and update) this page quite easily so I do not mind keeping it alive.  Will do so.  But also I agree with @HansOlsson . 

Projects to add: OpenScaling, @MartinOtter, how was the predecessor called?
